######################################################################################################################
## EDB DDL Extractor Utility. Version: 2.3.8
##
## Source Database Version: Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
##
## Extracted On: 29-09-2021 20:17:04
######################################################################################################################
########################################
## SYNONYM
########################################
########################################
## DATABASE LINKS
########################################
########################################
## TYPE SPECIFICATION
########################################
########################################
## TYPE BODY
########################################
########################################
## SEQUENCES
########################################
--START_OF_DDL
   CREATE SEQUENCE  "LEARNINGSQL"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--END_OF_DDL

########################################
## TABLE DDL
########################################
--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."ACCOUNT"
   (	"ACCOUNT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"AVAIL_BALANCE" FLOAT(126),
	"CLOSE_DATE" DATE,
	"LAST_ACTIVITY_DATE" DATE,
	"OPEN_DATE" DATE NOT NULL ENABLE,
	"PENDING_BALANCE" FLOAT(126),
	"STATUS" VARCHAR2(10 CHAR),
	"CUST_ID" NUMBER(10,0),
	"OPEN_BRANCH_ID" NUMBER(10,0) NOT NULL ENABLE,
	"OPEN_EMP_ID" NUMBER(10,0) NOT NULL ENABLE,
	"PRODUCT_CD" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	 PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."ACC_TRANSACTION"
   (	"TXN_ID" NUMBER(19,0) NOT NULL ENABLE,
	"AMOUNT" FLOAT(126) NOT NULL ENABLE,
	"FUNDS_AVAIL_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"TXN_DATE" TIMESTAMP (6) NOT NULL ENABLE,
	"TXN_TYPE_CD" VARCHAR2(10 CHAR),
	"ACCOUNT_ID" NUMBER(10,0),
	"EXECUTION_BRANCH_ID" NUMBER(10,0),
	"TELLER_EMP_ID" NUMBER(10,0),
	 PRIMARY KEY ("TXN_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."BRANCH"
   (	"BRANCH_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(30 CHAR),
	"CITY" VARCHAR2(20 CHAR),
	"NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"STATE" VARCHAR2(10 CHAR),
	"ZIP_CODE" VARCHAR2(12 CHAR),
	 PRIMARY KEY ("BRANCH_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."BUSINESS"
   (	"INCORP_DATE" DATE,
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"STATE_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE,
	 PRIMARY KEY ("CUST_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."CUSTOMER"
   (	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(30 CHAR),
	"CITY" VARCHAR2(20 CHAR),
	"CUST_TYPE_CD" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"FED_ID" VARCHAR2(12 CHAR) NOT NULL ENABLE,
	"POSTAL_CODE" VARCHAR2(10 CHAR),
	"STATE" VARCHAR2(20 CHAR),
	 PRIMARY KEY ("CUST_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."DEPARTMENT"
   (	"DEPT_ID" NUMBER(10,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	 PRIMARY KEY ("DEPT_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."EMPLOYEE"
   (	"EMP_ID" NUMBER(10,0) NOT NULL ENABLE,
	"END_DATE" DATE,
	"FIRST_NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"TITLE" VARCHAR2(20 CHAR),
	"ASSIGNED_BRANCH_ID" NUMBER(10,0),
	"DEPT_ID" NUMBER(10,0),
	"SUPERIOR_EMP_ID" NUMBER(10,0),
	 PRIMARY KEY ("EMP_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."INDIVIDUAL"
   (	"BIRTH_DATE" DATE,
	"FIRST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"CUST_ID" NUMBER(10,0) NOT NULL ENABLE,
	 PRIMARY KEY ("CUST_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."OFFICER"
   (	"OFFICER_ID" NUMBER(10,0) NOT NULL ENABLE,
	"END_DATE" DATE,
	"FIRST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"LAST_NAME" VARCHAR2(30 CHAR) NOT NULL ENABLE,
	"START_DATE" DATE NOT NULL ENABLE,
	"TITLE" VARCHAR2(20 CHAR),
	"CUST_ID" NUMBER(10,0),
	 PRIMARY KEY ("OFFICER_ID")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."PRODUCT"
   (	"PRODUCT_CD" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"DATE_OFFERED" DATE,
	"DATE_RETIRED" DATE,
	"NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"PRODUCT_TYPE_CD" VARCHAR2(255 CHAR),
	 PRIMARY KEY ("PRODUCT_CD")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

--START_OF_DDL
  CREATE TABLE "LEARNINGSQL"."PRODUCT_TYPE"
   (	"PRODUCT_TYPE_CD" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"NAME" VARCHAR2(50 CHAR),
	 PRIMARY KEY ("PRODUCT_TYPE_CD")
  USING INDEX  ENABLE
   ) ;
--END_OF_DDL

########################################
## PARTITION TABLE DDL
########################################
########################################
## CACHE TABLE DDL
########################################
########################################
## CLUSTER TABLE DDL
########################################
########################################
## KEEP TABLE DDL
########################################
########################################
## IOT TABLE DDL
########################################
########################################
## COMPRESSED TABLE DDL
########################################
########################################
## EXTERNAL TABLE DDL
########################################
########################################
## INDEXES DDL
########################################
########################################
## CONSTRAINTS
########################################
## Foreign Keys
###############

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_BRANCH_FK" FOREIGN KEY ("OPEN_BRANCH_ID")
	  REFERENCES "LEARNINGSQL"."BRANCH" ("BRANCH_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_CUSTOMER_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "LEARNINGSQL"."CUSTOMER" ("CUST_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_EMPLOYEE_FK" FOREIGN KEY ("OPEN_EMP_ID")
	  REFERENCES "LEARNINGSQL"."EMPLOYEE" ("EMP_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACCOUNT" ADD CONSTRAINT "ACCOUNT_PRODUCT_FK" FOREIGN KEY ("PRODUCT_CD")
	  REFERENCES "LEARNINGSQL"."PRODUCT" ("PRODUCT_CD") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_ACCOUNT_FK" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "LEARNINGSQL"."ACCOUNT" ("ACCOUNT_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_BRANCH_FK" FOREIGN KEY ("EXECUTION_BRANCH_ID")
	  REFERENCES "LEARNINGSQL"."BRANCH" ("BRANCH_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."ACC_TRANSACTION" ADD CONSTRAINT "ACC_TRANSACTION_EMPLOYEE_FK" FOREIGN KEY ("TELLER_EMP_ID")
	  REFERENCES "LEARNINGSQL"."EMPLOYEE" ("EMP_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."BUSINESS" ADD CONSTRAINT "BUSINESS_EMPLOYEE_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "LEARNINGSQL"."CUSTOMER" ("CUST_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_BRANCH_FK" FOREIGN KEY ("ASSIGNED_BRANCH_ID")
	  REFERENCES "LEARNINGSQL"."BRANCH" ("BRANCH_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_DEPARTMENT_FK" FOREIGN KEY ("DEPT_ID")
	  REFERENCES "LEARNINGSQL"."DEPARTMENT" ("DEPT_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_EMPLOYEE_FK" FOREIGN KEY ("SUPERIOR_EMP_ID")
	  REFERENCES "LEARNINGSQL"."EMPLOYEE" ("EMP_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."INDIVIDUAL" ADD CONSTRAINT "INDIVIDUAL_CUSTOMER_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "LEARNINGSQL"."CUSTOMER" ("CUST_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."OFFICER" ADD CONSTRAINT "OFFICER_CUSTOMER_FK" FOREIGN KEY ("CUST_ID")
	  REFERENCES "LEARNINGSQL"."CUSTOMER" ("CUST_ID") ENABLE;
--END_OF_DDL

--START_OF_DDL
  ALTER TABLE "LEARNINGSQL"."PRODUCT" ADD CONSTRAINT "PRODUCT_PRODUCT_TYPE_FK" FOREIGN KEY ("PRODUCT_TYPE_CD")
	  REFERENCES "LEARNINGSQL"."PRODUCT_TYPE" ("PRODUCT_TYPE_CD") ENABLE;
--END_OF_DDL

########################################
## VIEWS
########################################
########################################
## MATERIALIZED VIEWS
########################################
########################################
## TRIGGERS
########################################
########################################
## FUNCTIONS
########################################
########################################
## PROCEDURES
########################################
########################################
## PACKAGE SPECIFICATION
########################################
########################################
## PACKAGE BODY
########################################

## 1 Schema(s) Extracted Successfully:  LEARNINGSQL

## Extraction Completed: 29-09-2021 20:17:29
